
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/glade/u/apps/derecho/24.12/spack/opt/spack/cmake/3.26.6/gcc/12.4.0/okco/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Linux - 5.14.21-150400.24.81_12.0.75-cray_shasta_c - x86_64
