name: Run request
description: This is for CAM developpers who requested a new development simulation.
title: "One line description for your simulation request"
labels: ["Run request"]

body:
  - type: textarea
    id: Description
    attributes:
      label: Description of the run
      description: Please enter a short description of the run here
      placeholder: Tell us what you see!
      value: "Short description of the run [Required]"
    validations:
      required: true

  - type: textarea
    id: Namelist
    attributes:
      label: Namelist modifications
      description: Enter any namelist modification.
      value: "Enter any namelist modification [Optional]"

  - type: textarea
    id: Source Mods
    attributes:
      label: Source modifications
      description: Enter any source modification.
      value: "Enter any source modification [Optional]"
      
  - type: textarea
    id: Sandbox
    attributes:
      label: Sandbox
      description: If you require the run to be done with a specific sandbox, please enter the info.
      value: "Enter sandbox location [Optional]"

  - type: textarea
    id: Contact
    attributes:
      label: Contact info
      description: Enter the contact information (person who did the run, science lead, etc...)
      value: "Enter contact information"

  - type: textarea
    id: other
    attributes:
      label: Any other relevant information
      description: Please enter any relevant information/comments about this run.
      value: "Enter relevant info"
