name: Run request
description: CAM developers, this is where to enter information about your run requests (for a new development simulation).
title: "One line description for your simulation request"
labels: ["Issue type: Run request"]

body:
  - type: textarea
    id: Description
    attributes:
      label: Description of the run
      description: Please enter a short escription of the run and its purpose
      value: "Short description of the run [Required]"
    validations:
      required: true

  - type: textarea
    id: Namelist
    attributes:
      label: Namelist modifications
      description: Please enter any namelist modification.
      value: "Namelist modification [Optional]"

  - type: textarea
    id: SourceMods
    attributes:
      label: Source modifications
      description: Please enter any source modification.
      value: "Source modification [Optional]"
      
  - type: textarea
    id: Sandbox
    attributes:
      label: Sandbox
      description: If you require the run to be done with a specific sandbox, please enter the info.
      value: "Requested sandbox or tag [Optional]"

  - type: textarea
    id: Contact
    attributes:
      label: Contact info
      description: Enter the contact information (person who did the run, science lead, etc...)
      value: "Contact information"  
    validations:
      required: true

  - type: textarea
    id: other
    attributes:
      label: Any other relevant information
      description: Please enter any relevant information/comments about this run.
      value: "Enter relevant info"
