name: Run request (in yaml)
description: Brief Summuary of the simulation you want. 
title: "Title for your simulation request"
labels: ["Run request"]
assignees:
  - Enter your name here

body:
  - type: textarea
    id: Description
    attributes:
      label: Description of the run
      description: Please enter a short description of the run here
      placeholder: Tell us what you see!
      value: "Enter Description"
    validations:
      required: true

  - type: textarea
    id: Casedir
    attributes:
      label: Namelist modifications
      description: Enter any namelist modification.
      value: "Enter any namelist modification"

  - type: textarea
    id: Sandbox
    attributes:
      label: Sandbox
      description: Enter the location of the sandbox on github and/or locally
      value: "Enter sandbox location"

  - type: textarea
    id: Contact
    attributes:
      label: Contact info
      description: Enter the contact information (person who did the run, science lead, etc...)
      value: "Enter contact information"

  - type: textarea
    id: other
    attributes:
      label: Any other relevant information
      description: Please enter any relevant information/comments about this run.
      value: "Enter relevant info"
