name: Simulation template (in yml) 
description: Documenting information about a CESM simulation you have performed
title: "Casename (enter the name of the run here)"
labels: ["AMWG"]
assignees:
  - Enter your name here
  
body:
  - type: textarea
    id: Description
    attributes:
      label: Description of the run
      description: Please enter a short description of the run here
      placeholder: Tell us what you see!
      value: "Enter Description"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Type of run
      description: What was the type of simulation?
      options:
        - Development (Default)
        - Production (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: Machine?
      multiple: true
      options:
        - Cheyenne
        - Deracheo
        - Isumi
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
