#!/bin/bash

#PBS -N timeseries
#PBS -q regular
#PBS -l select=16:ncpus=9:mpiprocs=9
#PBS -l walltime=12:00:00
#PBS -A None

source /etc/profile.d/modules.sh

export MPI_UNBUFFERED_STDIO=true
export TMPDIR=$TMPDIR


##########
##
## See https://github.com/NCAR/CESM_postprocessing/wiki for details
## regarding settings for optimal performance for CESM postprocessing tools.
##
##########

if [ ! -e /glade/p/cesm/postprocessing/cesm-env2/bin ]; then
    echo "*************************************************************************************"
    echo "CESM timeseries exiting due to non-existant python virtual environment in"
    echo "    /glade/p/cesm/postprocessing/cesm-env2/bin"
    echo "You must first run:"
    echo "$POSTPROCESS_PATH/create_python_env -machine [machine]"
    echo "*************************************************************************************"
    exit
fi


module purge




## activate the virtualenv that contains all the non-bootstrapped dependencies

cd /glade/p/cesm/postprocessing/cesm-env2/bin
echo "Running from virtualenv directory:"
pwd
. activate

## load the boot-strap modules 


module load gnu/8.3.0

module load ncarenv

module load ncarcompilers

module load mpt/2.19

module load netcdf/4.6.3

module load nco/4.7.9

module load ncl/6.6.2





today="$(date '+%Y%m%d-%H%M%S')"
log_filename=/glade/u/home/tilmes/cesm_dev/cesm2_ch/CAM7_tests/f.e21.FWscHIST_chemistry.ne30pg3_L58_cam6_3_041_control.001/postprocess/logs/timeseries.log.$today


mpiexec_mpt dplace -s 1 ./cesm_tseries_generator.py --debug 0  --caseroot /glade/u/home/tilmes/cesm_dev/cesm2_ch/CAM7_tests/f.e21.FWscHIST_chemistry.ne30pg3_L58_cam6_3_041_control.001/postprocess >> ${log_filename} 2>&1

