string(APPEND CFLAGS " -qopt-report -xCORE_AVX2 -no-fma")
string(APPEND FFLAGS " -qopt-report -xCORE_AVX2 -no-fma")
if (DEBUG)
  string(APPEND CMAKE_OPTS " -DPIO_ENABLE_LOGGING=ON")
endif()
if (MPILIB STREQUAL mpi-serial AND NOT compile_threaded)
  set(PFUNIT_PATH "$ENV{CESMDATAROOT}/tools/pFUnit/pFUnit4.7.0_cheyenne_Intel19.1.1_noMPI_noOpenMP")
endif()
set(HAS_F2008_CONTIGUOUS "TRUE")
