string(APPEND CFLAGS " -qno-opt-dynamic-align -fp-model precise -std=gnu99")
string(APPEND CXXFLAGS " -qno-opt-dynamic-align -fp-model precise -std=c++17")
if (NOT DEBUG)
  string(APPEND CFLAGS " -O2 -debug minimal -no-fma -restrict")
  string(APPEND CXXFLAGS " -O2 -debug minimal -no-fma -restrict")
  string(APPEND FFLAGS " -O2 -debug minimal -no-fma")
else()
  string(APPEND CFLAGS " -O0 -no-fma -g")
  string(APPEND CXXFLAGS " -O0 -no-fma -g -traceback")
  string(APPEND FFLAGS " -O0 -no-fma -g -check uninit -check bounds -check pointers -fpe0 -check noarg_temp_created")
endif()
string(APPEND CPPDEFS " -DFORTRANUNDERSCORE -DCPRINTEL")
string(APPEND CXX_LDFLAGS " -cxxlib")
set(CXX_LINKER "FORTRAN")
set(FC_AUTO_R8 "-r8")
string(APPEND FFLAGS " -qno-opt-dynamic-align  -convert big_endian -assume byterecl -ftz -traceback -assume realloc_lhs -fp-model source")
set(FFLAGS_NOOPT "-O0")
set(FIXEDFLAGS "-fixed")
set(FREEFLAGS "-free")
if (compile_threaded)
  string(APPEND CFLAGS " -qopenmp")
  string(APPEND CXXFLAGS " -qopenmp")
  string(APPEND FFLAGS " -qopenmp")
  string(APPEND LDFLAGS " -qopenmp")
endif()
set(MPICC "mpicc")
set(MPICXX "mpicxx")
set(MPIFC "mpif90")
set(SCC "icx")
set(SCXX "icpx")
set(SFC "ifort")
if (MPILIB STREQUAL mpi-serial)
  string(APPEND SLIBS " -mkl")
else()
  string(APPEND SLIBS " -mkl=cluster")
endif()
set(SUPPORTS_CXX "TRUE")
